
version: '3.8'
services:
  inventario:
    build:
      context: ../Inventario
    ports:
      - "8081:8080"
    volumes:
      - ./wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=orders
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@microservinventary_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=Inventario202506
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    networks:
      - backend

networks:
  backend:

    driver: bridge